/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const FulfillmentId: core.serialization.Schema<
    serializers.inventory.FulfillmentId.Raw,
    PackagexApi.inventory.FulfillmentId
> = core.serialization.string();

export declare namespace FulfillmentId {
    type Raw = string;
}
