/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const Inventory: core.serialization.ObjectSchema<
    serializers.inventory.Inventory.Raw,
    PackageX.inventory.Inventory
> = core.serialization.object({
    attributes: core.serialization
        .lazy(async () => (await import("../../../../..")).inventory.InventoryAttributes)
        .optional(),
    comment: core.serialization.string().optional(),
    createdAt: core.serialization.property("created_at", core.serialization.number().optional()),
    verifiedQty: core.serialization.property("verified_qty", core.serialization.number().optional()),
    damagedQty: core.serialization.property("damaged_qty", core.serialization.number().optional()),
    manifestedQty: core.serialization.property("manifested_qty", core.serialization.number().optional()),
    harmonizedCode: core.serialization.property("harmonized_code", core.serialization.string().optional()),
    id: core.serialization.string().optional(),
    gtin: core.serialization.string().optional(),
    sku: core.serialization.string().optional(),
    serialNumber: core.serialization.property("serial_number", core.serialization.string().optional()),
    imageUrl: core.serialization.property("image_url", core.serialization.string().optional()),
    name: core.serialization.string().optional(),
    originCountry: core.serialization.property("origin_country", core.serialization.string().optional()),
    vendor: core.serialization.string().optional(),
    value: core.serialization.number().optional(),
    packagedLength: core.serialization.property("packaged_length", core.serialization.number().optional()),
    packagedWidth: core.serialization.property("packaged_width", core.serialization.number().optional()),
    packagedHeight: core.serialization.property("packaged_height", core.serialization.number().optional()),
    packagedWeight: core.serialization.property("packaged_weight", core.serialization.number().optional()),
});

export declare namespace Inventory {
    interface Raw {
        attributes?: serializers.inventory.InventoryAttributes.Raw | null;
        comment?: string | null;
        created_at?: number | null;
        verified_qty?: number | null;
        damaged_qty?: number | null;
        manifested_qty?: number | null;
        harmonized_code?: string | null;
        id?: string | null;
        gtin?: string | null;
        sku?: string | null;
        serial_number?: string | null;
        image_url?: string | null;
        name?: string | null;
        origin_country?: string | null;
        vendor?: string | null;
        value?: number | null;
        packaged_length?: number | null;
        packaged_width?: number | null;
        packaged_height?: number | null;
        packaged_weight?: number | null;
    }
}
