/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const InventoryAttributes: core.serialization.Schema<
    serializers.inventory.InventoryAttributes.Raw,
    PackageX.inventory.InventoryAttributes
> = core.serialization.enum_(["alcohol", "marijuana", "pharma", "dry_ice", "lithium"]);

export declare namespace InventoryAttributes {
    type Raw = "alcohol" | "marijuana" | "pharma" | "dry_ice" | "lithium";
}
