/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const ParcelId: core.serialization.Schema<serializers.inventory.ParcelId.Raw, PackageX.inventory.ParcelId> =
    core.serialization.string();

export declare namespace ParcelId {
    type Raw = string;
}
