/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const Parcel: core.serialization.ObjectSchema<serializers.inventory.Parcel.Raw, PackagexApi.inventory.Parcel> =
    core.serialization.object({
        attributes: core.serialization
            .list(core.serialization.lazy(async () => (await import("../../../../..")).inventory.InventoryAttributes))
            .optional(),
        id: core.serialization.lazy(async () => (await import("../../../../..")).inventory.ParcelId),
        length: core.serialization.number(),
        width: core.serialization.number(),
        height: core.serialization.number(),
        weight: core.serialization.number().optional(),
        type: core.serialization.lazy(async () => (await import("../../../../..")).PackageType).optional(),
        specialHandling: core.serialization.property("special_handling", core.serialization.string().optional()),
        trackingNumber: core.serialization.property("tracking_number", core.serialization.string().optional()),
        labelUrl: core.serialization.property("label_url", core.serialization.string().optional()),
        inventory: core.serialization
            .lazyObject(async () => (await import("../../../../..")).inventory.Inventory)
            .optional(),
    });

export declare namespace Parcel {
    interface Raw {
        attributes?: serializers.inventory.InventoryAttributes.Raw[] | null;
        id: serializers.inventory.ParcelId.Raw;
        length: number;
        width: number;
        height: number;
        weight?: number | null;
        type?: serializers.PackageType.Raw | null;
        special_handling?: string | null;
        tracking_number?: string | null;
        label_url?: string | null;
        inventory?: serializers.inventory.Inventory.Raw | null;
    }
}
