/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const ShipmentRateType: core.serialization.Schema<
    serializers.inventory.ShipmentRateType.Raw,
    PackagexApi.inventory.ShipmentRateType
> = core.serialization.enum_([
    "in_person_pickup",
    "curbside_pickup",
    "locker_pickup",
    "provider_delivery",
    "offline_delivery",
]);

export declare namespace ShipmentRateType {
    type Raw = "in_person_pickup" | "curbside_pickup" | "locker_pickup" | "provider_delivery" | "offline_delivery";
}
