/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface InventoryLevel {
    /** The ID for the level that starts with lvl_ */
    id: string;
    /** The ID of the location this in which this inventory level is housed */
    locationId: string;
    /** The layout ID within the location where this inventory can be found */
    layoutId?: string;
    /** The name of the layout this item is on. */
    layoutName?: string;
    /** The amount of on hand inventory. */
    verifiedQty?: number;
    /** The amount of on hand inventory that is deemed damaged */
    damagedQty?: number;
    /** The amount of inventory that is on a manifest that has not been added to inventory yet */
    manifestedQty?: number;
    /** Inventory that has been reserved by being pulled out of the verified_qty count, usually due to being attributed to a fulfillment */
    reservedQty?: number;
}
