/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

/**
 * @example
 *     {
 *         createdAt: 1679591515,
 *         id: "debebw3933hden",
 *         name: "My item name",
 *         sku: "123345",
 *         gtin: "987654",
 *         packagedLength: 5,
 *         packagedWidth: 6,
 *         packagedHeight: 7,
 *         packagedWeight: 8,
 *         status: "created"
 *     }
 *
 * @example
 *     {
 *         createdAt: 1679591515,
 *         id: "debebw3933hden",
 *         name: "Updated Name",
 *         sku: "123345",
 *         gtin: "987654",
 *         packagedLength: 5,
 *         packagedWidth: 6,
 *         packagedHeight: 7,
 *         packagedWeight: 8,
 *         status: "created",
 *         updatedAt: 1679591515,
 *         levels: [{
 *                 locationId: "loc_8GiCVuqZqBJi43v2WebaME",
 *                 verifiedQty: 60,
 *                 id: "lvl_dnqwn23ir23irb23rb23uibc"
 *             }, {
 *                 locationId: "loc_dKa43ncARLdGENQPUq2CoX",
 *                 verifiedQty: 10,
 *                 id: "lvl_fewfwef90c803cecee"
 *             }]
 *     }
 */
export interface Item {
    attributes?: PackageX.inventory.InventoryAttributes;
    /** Any value can be added here */
    color?: string;
    /** Time in epoch seconds when this resource was created */
    createdAt: number;
    /** The details about the item */
    description?: string;
    /** The global identifier for the item, which is consistent across vendors for this item */
    gtin?: string;
    /** The harmonized system code for the item. This is required if you will be shipping this item internationally. */
    harmonizedCode?: string;
    /** The unique ID given to this product. This will stay the same even if the SKU or GTIN values are updated. */
    id: PackageX.inventory.ItemId;
    /** A list of URLs of images that have been added for this item */
    images?: string[];
    /** Information about inventory levels for this item across various locations and layouts */
    levels?: PackageX.inventory.InventoryLevel[];
    /** Any custom metadata that you have added */
    metadata?: Record<string, unknown>;
    /** The name of the item */
    name: string;
    /** The length of the item in inches */
    length?: number;
    /** The width of the item in inches */
    width?: number;
    /** The height of the item in inches */
    height?: number;
    /** The weight of the item in pounds (lbs) */
    weight?: number;
    /** The length of the item in inches when placed in shipping packaging */
    packagedLength?: number;
    /** The width of the item in inches when placed in shipping packaging */
    packagedWidth?: number;
    /** The height of the item in inches when placed in shipping packaging */
    packagedHeight?: number;
    /** The weight of the item in pounds (lbs) when placed in shipping packaging */
    packagedWeight?: number;
    /** The country that manufactured this item. This is required if shipping the item internationally */
    originCountry?: string;
    /** The unique identifier for the organization that owns this item. This will always be your organization ID */
    organizationId?: string;
    status?: string;
    /** The size of the item. This is used for display purposes on a product page. This is common when adding something like a "small" or "large" variation. */
    size?: string;
    /** The SKU of the item added by you */
    sku?: string;
    /** The total verified inventory count across all levels */
    totalVerified?: number;
    /** The total damaged inventory count across all levels */
    totalDamaged?: number;
    /** The total inventory count that is on a manifest */
    totalManifested?: number;
    /** The total inventory count that is reserved */
    totalReserved?: number;
    /** Time in epoch seconds when this resource was updated */
    updatedAt?: number;
    /** The value of this each individual item in cents */
    value?: number;
}
