/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

export interface ListItemResponse extends PackageX.Response {
    data: PackageX.inventory.Item[];
}
