/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments";
import * as core from "../../../../core";
import { Fulfillment } from "../resources/fulfillment/client/Client";
import { Item } from "../resources/item/client/Client";
import { Manifest } from "../resources/manifest/client/Client";

export declare namespace Inventory {
    interface Options {
        environment?: environments.PackageXEnvironment | string;
        apiKey: core.Supplier<string>;
    }
}

export class Inventory {
    constructor(private readonly options: Inventory.Options) {}

    private _fulfillment: Fulfillment | undefined;

    public get fulfillment(): Fulfillment {
        return (this._fulfillment ??= new Fulfillment(this.options));
    }

    private _item: Item | undefined;

    public get item(): Item {
        return (this._item ??= new Item(this.options));
    }

    private _manifest: Manifest | undefined;

    public get manifest(): Manifest {
        return (this._manifest ??= new Manifest(this.options));
    }
}
