/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../../../core";

export const UpdateItemRequest: core.serialization.Schema<
    serializers.inventory.UpdateItemRequest.Raw,
    PackagexApi.inventory.UpdateItemRequest
> = core.serialization.object({
    name: core.serialization.string().optional(),
    levels: core.serialization
        .list(core.serialization.lazyObject(async () => (await import("../../../../../..")).inventory.InventoryLevel))
        .optional(),
});

export declare namespace UpdateItemRequest {
    interface Raw {
        name?: string | null;
        levels?: serializers.inventory.InventoryLevel.Raw[] | null;
    }
}
