/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Address: core.serialization.Schema<serializers.Address.Raw, PackageX.Address> =
    core.serialization.undiscriminatedUnion([
        core.serialization.string(),
        core.serialization.lazyObject(async () => (await import("../../..")).ParsedAddress),
    ]);

export declare namespace Address {
    type Raw = string | serializers.ParsedAddress.Raw;
}
