/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const AddressSuggestion: core.serialization.ObjectSchema<
    serializers.AddressSuggestion.Raw,
    PackageX.AddressSuggestion
> = core.serialization.object({
    address: core.serialization.string(),
    matchedText: core.serialization.property("matched_text", core.serialization.string()),
    autocompleteText: core.serialization.property("autocomplete_text", core.serialization.string()),
});

export declare namespace AddressSuggestion {
    interface Raw {
        address: string;
        matched_text: string;
        autocomplete_text: string;
    }
}
