/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const AddressId: core.serialization.Schema<serializers.AddressId.Raw, PackageX.AddressId> =
    core.serialization.string();

export declare namespace AddressId {
    type Raw = string;
}
