/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../../core";

export const CreateFulfillmentRequest: core.serialization.Schema<
    serializers.inventory.CreateFulfillmentRequest.Raw,
    PackageX.inventory.CreateFulfillmentRequest
> = core.serialization.object({
    recipient: core.serialization.lazyObject(async () => (await import("../../../../../..")).Recipient),
    locationId: core.serialization.property("location_id", core.serialization.string()),
    inventory: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../../../..")).inventory.Inventory)
    ),
});

export declare namespace CreateFulfillmentRequest {
    interface Raw {
        recipient: serializers.Recipient.Raw;
        location_id: string;
        inventory: serializers.inventory.Inventory.Raw[];
    }
}
