/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../../../core";

export const PackParcelRequest: core.serialization.Schema<
    serializers.inventory.PackParcelRequest.Raw,
    PackagexApi.inventory.PackParcelRequest
> = core.serialization.object({
    inventory: core.serialization.list(
        core.serialization.lazyObject(async () => (await import("../../../../../..")).inventory.Inventory)
    ),
});

export declare namespace PackParcelRequest {
    interface Raw {
        inventory: serializers.inventory.Inventory.Raw[];
    }
}
