/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../../core";

export const UpdateFulfillmentRequest: core.serialization.Schema<
    serializers.inventory.UpdateFulfillmentRequest.Raw,
    PackageX.inventory.UpdateFulfillmentRequest
> = core.serialization.object({
    status: core.serialization.lazy(async () => (await import("../../../../../..")).inventory.FulfillmentStatus),
});

export declare namespace UpdateFulfillmentRequest {
    interface Raw {
        status: serializers.inventory.FulfillmentStatus.Raw;
    }
}
