/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

export interface GetShipmentRatesRequest {
    sender: PackageX.Sender;
    recipient: PackageX.Recipient;
    parcel: PackageX.ParcelShipment;
    options?: PackageX.ShipmentOptions;
}
