/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

export interface PurchaseShipmentRateRequest {
    /** The ID of the rate that you wish to purchase */
    rateId: string;
    /** The ID of the payment method that you want to use from the payment methods you have on file with PackageX. If not provided, we'll use the default payment method on file */
    paymentMethod?: string;
    /** A reference to the payment that can be added to this shipment. This is a field generated by the user */
    paymentReference: string;
    labelSize: PackagexApi.LabelSize;
}
