/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../core";

export const GetShipmentRatesRequest: core.serialization.Schema<
    serializers.GetShipmentRatesRequest.Raw,
    PackageX.GetShipmentRatesRequest
> = core.serialization.object({
    sender: core.serialization.lazyObject(async () => (await import("../../../..")).Sender),
    recipient: core.serialization.lazyObject(async () => (await import("../../../..")).Recipient),
    parcel: core.serialization.lazyObject(async () => (await import("../../../..")).ParcelShipment),
    options: core.serialization.lazyObject(async () => (await import("../../../..")).ShipmentOptions).optional(),
});

export declare namespace GetShipmentRatesRequest {
    interface Raw {
        sender: serializers.Sender.Raw;
        recipient: serializers.Recipient.Raw;
        parcel: serializers.ParcelShipment.Raw;
        options?: serializers.ShipmentOptions.Raw | null;
    }
}
