/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../core";

export const PurchaseShipmentRateRequest: core.serialization.Schema<
    serializers.PurchaseShipmentRateRequest.Raw,
    PackagexApi.PurchaseShipmentRateRequest
> = core.serialization.object({
    rateId: core.serialization.property("rate_id", core.serialization.string()),
    paymentMethod: core.serialization.property("payment_method", core.serialization.string().optional()),
    paymentReference: core.serialization.property("payment_reference", core.serialization.string()),
    labelSize: core.serialization.property(
        "label_size",
        core.serialization.lazy(async () => (await import("../../../..")).LabelSize)
    ),
});

export declare namespace PurchaseShipmentRateRequest {
    interface Raw {
        rate_id: string;
        payment_method?: string | null;
        payment_reference: string;
        label_size: serializers.LabelSize.Raw;
    }
}
