/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../core";

export const RefetchShipmentRatesRequest: core.serialization.Schema<
    serializers.RefetchShipmentRatesRequest.Raw,
    PackageX.RefetchShipmentRatesRequest
> = core.serialization.object({
    options: core.serialization.lazyObject(async () => (await import("../../../..")).ShipmentOptions).optional(),
});

export declare namespace RefetchShipmentRatesRequest {
    interface Raw {
        options?: serializers.ShipmentOptions.Raw | null;
    }
}
