/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Currency: core.serialization.Schema<serializers.Currency.Raw, PackageX.Currency> =
    core.serialization.enum_(["usd"]);

export declare namespace Currency {
    type Raw = "usd";
}
