/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const LabelSize: core.serialization.Schema<serializers.LabelSize.Raw, PackagexApi.LabelSize> =
    core.serialization.enum_(["4x6", "letter", "4x8", "a4", "a6"]);

export declare namespace LabelSize {
    type Raw = "4x6" | "letter" | "4x8" | "a4" | "a6";
}
