/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ParcelShipment: core.serialization.ObjectSchema<
    serializers.ParcelShipment.Raw,
    PackagexApi.ParcelShipment
> = core.serialization.object({
    length: core.serialization.number().optional(),
    width: core.serialization.number().optional(),
    height: core.serialization.number().optional(),
    weight: core.serialization.number().optional(),
    type: core.serialization.lazy(async () => (await import("../../..")).PackageType).optional(),
    specialHandling: core.serialization.property(
        "special_handling",
        core.serialization.lazy(async () => (await import("../../..")).SpecialHandling).optional()
    ),
    inventory: core.serialization.lazyObject(async () => (await import("../../..")).inventory.Inventory).optional(),
});

export declare namespace ParcelShipment {
    interface Raw {
        length?: number | null;
        width?: number | null;
        height?: number | null;
        weight?: number | null;
        type?: serializers.PackageType.Raw | null;
        special_handling?: serializers.SpecialHandling.Raw | null;
        inventory?: serializers.inventory.Inventory.Raw | null;
    }
}
