/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const RateTypes: core.serialization.Schema<serializers.RateTypes.Raw, PackageX.RateTypes> =
    core.serialization.enum_([
        "in_person_pickup",
        "curbside_pickup",
        "locker_pickup",
        "provider_delivery",
        "offline_delivery",
    ]);

export declare namespace RateTypes {
    type Raw = "in_person_pickup" | "curbside_pickup" | "locker_pickup" | "provider_delivery" | "offline_delivery";
}
