/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const RefundStatus: core.serialization.Schema<serializers.RefundStatus.Raw, PackageX.RefundStatus> =
    core.serialization.enum_(["requested", "refunded", "rejected"]);

export declare namespace RefundStatus {
    type Raw = "requested" | "refunded" | "rejected";
}
