/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ServiceLevel: core.serialization.ObjectSchema<serializers.ServiceLevel.Raw, PackageX.ServiceLevel> =
    core.serialization.object({
        name: core.serialization.string(),
        id: core.serialization.string(),
        terms: core.serialization.string(),
        days: core.serialization.number(),
        estimatedDelivery: core.serialization.property("estimated_delivery", core.serialization.number()),
        pickupAt: core.serialization.property("pickup_at", core.serialization.number()),
    });

export declare namespace ServiceLevel {
    interface Raw {
        name: string;
        id: string;
        terms: string;
        days: number;
        estimated_delivery: number;
        pickup_at: number;
    }
}
