/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ShipmentStatus: core.serialization.Schema<serializers.ShipmentStatus.Raw, PackageX.ShipmentStatus> =
    core.serialization.enum_([
        "rates_generated",
        "created",
        "address_issue",
        "provider_at_pickup",
        "contact_provider",
        "delayed",
        "delivery_attempted",
        "delivery_rescheduled",
        "delivery_scheduled",
        "out_for_delivery",
        "package_accepted",
        "package_at_waypoint",
        "in_transit",
        "pickup_available",
        "provider_at_dropoff",
        "package_damaged",
        "delivered",
        "return_to_sender",
        "package_undeliverable",
        "package_lost",
        "canceled",
    ]);

export declare namespace ShipmentStatus {
    type Raw =
        | "rates_generated"
        | "created"
        | "address_issue"
        | "provider_at_pickup"
        | "contact_provider"
        | "delayed"
        | "delivery_attempted"
        | "delivery_rescheduled"
        | "delivery_scheduled"
        | "out_for_delivery"
        | "package_accepted"
        | "package_at_waypoint"
        | "in_transit"
        | "pickup_available"
        | "provider_at_dropoff"
        | "package_damaged"
        | "delivered"
        | "return_to_sender"
        | "package_undeliverable"
        | "package_lost"
        | "canceled";
}
