/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ShipmentOptions: core.serialization.ObjectSchema<
    serializers.ShipmentOptions.Raw,
    PackageX.ShipmentOptions
> = core.serialization.object({
    providerTimeout: core.serialization.property("provider_timeout", core.serialization.number().optional()),
    verifyAddress: core.serialization.property("verify_address", core.serialization.boolean().optional()),
    checkoutTotal: core.serialization.property("checkout_total", core.serialization.number().optional()),
    requestProviderPickup: core.serialization.property(
        "request_provider_pickup",
        core.serialization.boolean().optional()
    ),
    providers: core.serialization.list(core.serialization.string()).optional(),
    serviceLevels: core.serialization.property(
        "service_levels",
        core.serialization.list(core.serialization.string()).optional()
    ),
    maxDeliveryDays: core.serialization.property("max_delivery_days", core.serialization.number().optional()),
    rateTypes: core.serialization.property(
        "rate_types",
        core.serialization.list(core.serialization.lazy(async () => (await import("../../..")).RateTypes)).optional()
    ),
});

export declare namespace ShipmentOptions {
    interface Raw {
        provider_timeout?: number | null;
        verify_address?: boolean | null;
        checkout_total?: number | null;
        request_provider_pickup?: boolean | null;
        providers?: string[] | null;
        service_levels?: string[] | null;
        max_delivery_days?: number | null;
        rate_types?: serializers.RateTypes.Raw[] | null;
    }
}
