/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ShipmentFeedback: core.serialization.ObjectSchema<
    serializers.ShipmentFeedback.Raw,
    PackagexApi.ShipmentFeedback
> = core.serialization.object({
    rating: core.serialization.lazy(async () => (await import("../../..")).FeedbackRating).optional(),
    comment: core.serialization.string().optional(),
    updatedAt: core.serialization.property("updated_at", core.serialization.number().optional()),
});

export declare namespace ShipmentFeedback {
    interface Raw {
        rating?: serializers.FeedbackRating.Raw | null;
        comment?: string | null;
        updated_at?: number | null;
    }
}
