/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ShipmentEvent: core.serialization.Schema<serializers.ShipmentEvent.Raw, PackageX.ShipmentEvent> =
    core.serialization.enum_([
        "shipment.rates_generated",
        "shipment.expired",
        "shipment.purchased",
        "shipment.tracking_updated",
        "shipment.canceled",
        "shipment.refunded",
        "shipment.coordinates_updated",
    ]);

export declare namespace ShipmentEvent {
    type Raw =
        | "shipment.rates_generated"
        | "shipment.expired"
        | "shipment.purchased"
        | "shipment.tracking_updated"
        | "shipment.canceled"
        | "shipment.refunded"
        | "shipment.coordinates_updated";
}
