/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const ShipmentId: core.serialization.Schema<serializers.ShipmentId.Raw, PackageX.ShipmentId> =
    core.serialization.string();

export declare namespace ShipmentId {
    type Raw = string;
}
