/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const ListManifestResponse: core.serialization.ObjectSchema<
    serializers.inventory.ListManifestResponse.Raw,
    PackagexApi.inventory.ListManifestResponse
> = core.serialization
    .object({
        data: core.serialization.list(
            core.serialization.lazyObject(async () => (await import("../../../../..")).inventory.Manifest)
        ),
    })
    .extend(core.serialization.lazyObject(async () => (await import("../../../../..")).Response));

export declare namespace ListManifestResponse {
    interface Raw extends serializers.Response.Raw {
        data: serializers.inventory.Manifest.Raw[];
    }
}
