/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const ManifestStatus: core.serialization.Schema<
    serializers.inventory.ManifestStatus.Raw,
    PackageX.inventory.ManifestStatus
> = core.serialization.enum_(["requested", "accepted", "processing", "completed", "void"]);

export declare namespace ManifestStatus {
    type Raw = "requested" | "accepted" | "processing" | "completed" | "void";
}
