/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

export interface CreateFulfillmentRequest {
    recipient: PackageX.Recipient;
    /** The ID of the location to which this manifest is being delivered */
    locationId: string;
    /** The inventory that needs to be shipped in this fulfillment */
    inventory: PackageX.inventory.Inventory[];
}
