/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

export interface PackParcelRequest {
    inventory: PackageX.inventory.Inventory[];
}
