/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const CreateShipmentRequest: core.serialization.ObjectSchema<
    serializers.CreateShipmentRequest.Raw,
    PackagexApi.CreateShipmentRequest
> = core.serialization.object({
    sender: core.serialization.lazyObject(async () => (await import("../../..")).Sender),
    recipient: core.serialization.lazyObject(async () => (await import("../../..")).Recipient),
    parcel: core.serialization.lazyObject(async () => (await import("../../..")).Parcel),
});

export declare namespace CreateShipmentRequest {
    interface Raw {
        sender: serializers.Sender.Raw;
        recipient: serializers.Recipient.Raw;
        parcel: serializers.Parcel.Raw;
    }
}
