/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const FeedbackRating: core.serialization.Schema<serializers.FeedbackRating.Raw, PackagexApi.FeedbackRating> =
    core.serialization.number();

export declare namespace FeedbackRating {
    type Raw = number;
}
