/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const LatestLocation: core.serialization.ObjectSchema<
    serializers.LatestLocation.Raw,
    PackagexApi.LatestLocation
> = core.serialization.object({
    latitude: core.serialization.number(),
    longitude: core.serialization.number(),
    updatedAt: core.serialization.property("updated_at", core.serialization.number()),
    mapUrl: core.serialization.property("map_url", core.serialization.string()),
});

export declare namespace LatestLocation {
    interface Raw {
        latitude: number;
        longitude: number;
        updated_at: number;
        map_url: string;
    }
}
