/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Parcel: core.serialization.ObjectSchema<serializers.Parcel.Raw, PackagexApi.Parcel> =
    core.serialization.object({
        length: core.serialization.number(),
        width: core.serialization.number(),
        height: core.serialization.number(),
        weight: core.serialization.number(),
        type: core.serialization.string(),
        itemDocs: core.serialization.property("item_docs", core.serialization.string()),
        specialHandling: core.serialization.property("special_handling", core.serialization.string()),
    });

export declare namespace Parcel {
    interface Raw {
        length: number;
        width: number;
        height: number;
        weight: number;
        type: string;
        item_docs: string;
        special_handling: string;
    }
}
