/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Provider: core.serialization.ObjectSchema<serializers.Provider.Raw, PackagexApi.Provider> =
    core.serialization.object({
        name: core.serialization.string(),
        id: core.serialization.string(),
        logoUrl: core.serialization.property("logo_url", core.serialization.string()),
        supportEmail: core.serialization.property("support_email", core.serialization.string()),
        supportPhone: core.serialization.property("support_phone", core.serialization.string()),
        supportUrl: core.serialization.property("support_url", core.serialization.string()),
        marketplace: core.serialization.boolean(),
    });

export declare namespace Provider {
    interface Raw {
        name: string;
        id: string;
        logo_url: string;
        support_email: string;
        support_phone: string;
        support_url: string;
        marketplace: boolean;
    }
}
