/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Response: core.serialization.ObjectSchema<serializers.Response.Raw, PackagexApi.Response> =
    core.serialization.object({
        status: core.serialization.number(),
        message: core.serialization.string(),
        errorCode: core.serialization.property("error_code", core.serialization.string()),
        errors: core.serialization.list(core.serialization.string()),
        pagination: core.serialization.lazyObject(async () => (await import("../../..")).Pagination),
        events: core.serialization.list(core.serialization.string()),
        endpoint: core.serialization.string(),
    });

export declare namespace Response {
    interface Raw {
        status: number;
        message: string;
        error_code: string;
        errors: string[];
        pagination: serializers.Pagination.Raw;
        events: string[];
        endpoint: string;
    }
}
