/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Sender: core.serialization.ObjectSchema<serializers.Sender.Raw, PackagexApi.Sender> =
    core.serialization.object({
        address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
        name: core.serialization.string(),
        email: core.serialization.string(),
        phone: core.serialization.string(),
        logoUrl: core.serialization.property("logo_url", core.serialization.string()),
        id: core.serialization.string(),
    });

export declare namespace Sender {
    interface Raw {
        address: serializers.Address.Raw;
        name: string;
        email: string;
        phone: string;
        logo_url: string;
        id: string;
    }
}
