/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const TrackingUpdate: core.serialization.ObjectSchema<
    serializers.TrackingUpdate.Raw,
    PackagexApi.TrackingUpdate
> = core.serialization.object({
    address: core.serialization.lazyObject(async () => (await import("../../..")).Address),
    status: core.serialization.string(),
    comment: core.serialization.string(),
    images: core.serialization.list(core.serialization.string()),
    message: core.serialization.string(),
    event: core.serialization.string(),
    createdAt: core.serialization.property("created_at", core.serialization.number()),
});

export declare namespace TrackingUpdate {
    interface Raw {
        address: serializers.Address.Raw;
        status: string;
        comment: string;
        images: string[];
        message: string;
        event: string;
        created_at: number;
    }
}
