/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * All address objects ids will be prefixed with addr_ to make them easy to distinguish.
 *
 */
export type AddressId = string;
