/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

export interface AutocompleteAddressResponse extends PackagexApi.Response {
    data: PackagexApi.AddressSuggestion[];
}
