/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

/**
 * The PackageX address object
 *
 * @example
 *     {
 *         id: "defnewfed_93392",
 *         hash: "dac0efe_w9dw",
 *         line1: "500 7th Ave",
 *         line2: "Fl 10",
 *         city: "New York",
 *         state: "New York",
 *         stateCode: "NY",
 *         country: "United States",
 *         countryCode: "US",
 *         postalCode: "10018",
 *         formattedAddress: "500 7th Ave, Fl 10, New York, NY, 10018",
 *         textarea: "500 7th Ave",
 *         timezone: "EST",
 *         verified: true
 *     }
 *
 * @example
 *     {
 *         id: "fefewfe_9292",
 *         hash: "efneif_2921",
 *         line1: "600 B. Street",
 *         line2: "Suite 300",
 *         city: "San Diego",
 *         state: "California",
 *         stateCode: "CA",
 *         country: "United States",
 *         countryCode: "US",
 *         postalCode: "90101",
 *         formattedAddress: "600 B. Street, Suite 300 7th Ave, Fl 10, San Diego, California 90101",
 *         textarea: "600 B. Street",
 *         timezone: "PST",
 *         verified: true
 *     }
 */
export interface ParsedAddress {
    /** The ID for this address. Can be passed into any address field in the future to retrieve this exact address. */
    id: PackageX.AddressId;
    /** Similar to the address ID, the hash is a unique string that identifies the address but without the line2 property. */
    hash: string;
    /** The first line of the street address. */
    line1: string;
    /** The second line of the street address. */
    line2: string;
    /** The name of the city. */
    city: string;
    /** The full name of the state. */
    state: string;
    /** The abbreviated code for the state if applicable. */
    stateCode: string;
    /** The full name of the country for this address. */
    country: string;
    /** The two character country code for this address. */
    countryCode: string;
    /** The postal code for this address. */
    postalCode: string;
    /** The full text string of the address. */
    formattedAddress: string;
    /** The full text string of the address without the line2 address. This is useful if using address auto complete that does not provide a line2 address which would be asked for in a separate input field. */
    textarea: string;
    /** The timezone for this address */
    timezone: string;
    /** If we have verified this address */
    verified: boolean;
}
