/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The PackageX address object
 */
export interface Address {
    /** The ID for this address. Can be passed into any address field in the future to retrieve this exact address. */
    id: string;
    /** Similar to the address ID, the hash is a unique string that identifies the address but without the line2 property. */
    hash: string;
    /** The first line of the street address. */
    line1: string;
    /** The second line of the street address. */
    line2: string;
    /** The name of the city. */
    city: string;
    /** The full name of the state. */
    state: string;
    /** The abbreviated code for the state if applicable. */
    stateCode: string;
    /** The full name of the country for this address. */
    country: string;
    /** The two character country code for this address. */
    countryCode: string;
    /** The postal code for this address. */
    postalCode: string;
    /** The full text string of the address. */
    formattedAddress: string;
    /** The full text string of the address without the line2 address. This is useful if using address auto complete that does not provide a line2 address which would be asked for in a separate input field. */
    textarea: string;
    /** The timezone for this address */
    timezone: string;
    /** If we have verified this address */
    verified: boolean;
    /** The latitude coordinate */
    latitude: number;
    /** The longitude coordinate */
    longitude: number;
}
