/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The currency used for this shipment.
 */
export type Currency = "usd";

export const Currency = {
    Usd: "usd",
} as const;
