/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The latest read-time tracking information for this shipment
 */
export interface LatestLocation {
    /** The latitude coordinate available if the provider is giving real time updates */
    latitude: number;
    /** The longitude coordinate available if the provider is giving real time updates */
    longitude: number;
    /** The last time this live location was updated in epoch seconds */
    updatedAt: number;
    /** The url to a map showing the tracking history and current live location */
    mapUrl: string;
}
