/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A parcel or package that will be included in a shipment
 */
export interface Parcel {
    /** The length of the package in inches */
    length: number;
    /** The width of the package in inches */
    width: number;
    /** The height of the package in inches */
    height: number;
    /** The weight of the package in pounds */
    weight: number;
    /** The courier specific packaging. See https://docs.packagex.io/shipments/predefined-packages for more information */
    type: string;
    /** The user provided docs for the package. This is shown the the recipient if using PackageX notifications */
    itemDocs: string;
    /** Any special handing instructions provided. Not all shipping providers support these */
    specialHandling: string;
}
