/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details about a shipping provider for a given rate or shipment
 */
export interface Provider {
    /** The name of the provider */
    name: string;
    /** Unique ID of the provider */
    id: string;
    /** The url for the provider's logo */
    logoUrl: string;
    /** The contact email provided by the shipping provider */
    supportEmail: string;
    /** The contact phone provided by the shipping provider */
    supportPhone: string;
    /** The contact website provided by the shipping provider */
    supportUrl: string;
    /** If this shipping provider came from the PackageX marketplace. Typically large providers like FedEx, UPS, USPS, etc are not from the marketplace and same-day courier are not. */
    marketplace: boolean;
}
