/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The shipping rate object showing the service level, price, and shipping provider information
 */
export interface Rate {
    /** The ID for this rate. To purchase a shipping label after getting rates, you will pass in this rate to indicate you wish to purchase it */
    id: string;
    /** The amount that will be collected from a customer. This includes any upcharges or discounts you have added to the price on the PackageX Dashboard. */
    amount: number;
    /** The amount that your organization will be billed for this rate. */
    billedAmount: number;
    /** The custom rate card that was used for this transaction. Should be null for all organizations currently. */
    carrierAccount: string;
    /** Time in epoch seconds when this shipment will be picked up, if that is included in the service of this rate. Will be null otherwise. */
    pickupAt: number;
    provider: PackagexApi.Provider;
    serviceLevel: PackagexApi.ServiceLevel;
}
