/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The information about the shipment recipient
 */
export interface Recipient {
    address: PackagexApi.Address;
    /** The recipient's name */
    name: string;
    /** The recipient's email */
    email: string;
    /** The recipient's phone */
    phone: string;
}
