/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * An error response
 */
export interface Response {
    /** A 2XX code */
    status: number;
    /** A human readable message to display to an end user */
    message: string;
    /** The developer code for the issue that occurred. */
    errorCode: string;
    /** An list of errors that occurred. Normally will be of the properties that failed validation. */
    errors: string[];
    pagination: PackagexApi.Pagination;
    /** All of the events that were triggered due to this request */
    events: string[];
    /** The endpoint that was hit */
    endpoint: string;
}
