/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The information about the shipment sender, which is normally the organization using this API
 */
export interface Sender {
    address: PackagexApi.Address;
    /** The sender's name */
    name: string;
    /** The sender's email */
    email: string;
    /** The sender's phone */
    phone: string;
    /** The sender's logo */
    logoUrl: string;
    /** The sender's unique packagex ID */
    id: string;
}
