/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The service level for this rate
 */
export interface ServiceLevel {
    /** The human readable name for this service label */
    name: string;
    /** The unique ID of this provider's service level */
    id: string;
    /** The human readable delivery estimate for this rate */
    terms: string;
    /** The integer of days that this delivery is estimated to take if the provider receives the shipment before their daily cutoff time. */
    days: number;
    /** The time in epoch seconds when we estimate the shipment at this rate will be delivered */
    estimatedDelivery: number;
}
