/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The record of each tracking update from a shipment
 */
export interface TrackingUpdate {
    address: PackagexApi.Address;
    /** The status for this shipment. For all statuses see https://docs.packagex.io/shipments/statuses */
    status: string;
    /** A shipping provider comment */
    comment: string;
    /** Urls of images */
    images: string[];
    /** Human readable text explaining the status */
    message: string;
    /** The event that occurred when this event was created. For all events see https://docs.packagex.io/shipments/events */
    event: string;
    /** Time from unix eopch seconds when this tracking update was created */
    createdAt: number;
}
