/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

export interface ListManifestResponse extends PackagexApi.Response {
    data: PackagexApi.inventory.Manifest[];
}
