/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The manifest model represents a unique manifest containing the inventory that you would like to track.
 *
 * @example
 *     {
 *         createdAt: 1679591515,
 *         id: "msft_deuibcud2fwefwec33",
 *         locationId: "loc_afnHMjVUn3gnrvxU5zMvkX",
 *         status: PackagexApi.inventory.ManifestStatus.Accepted,
 *         inventory: [{
 *                 id: "item_pu8iNbturZy5zvB4zaUZ8t",
 *                 manifestedQty: 50
 *             }, {
 *                 sku: "DRC123",
 *                 manifestedQty: 50
 *             }, {
 *                 gtin: "123456789",
 *                 manifestedQty: 50
 *             }]
 *     }
 */
export interface Manifest {
    /** Time in epoch seconds when this resource was created */
    createdAt: number;
    /** Inventory must be created before the manifest can be acted upon. It is common for this to be empty. */
    createdInventory?: PackagexApi.inventory.Inventory[];
    /** Time in epoch seconds when we estimate the delivery will occur. */
    estimatedDelivery?: number;
    /** The unique ID given to this manifest prefixed with msft_ */
    id: PackagexApi.inventory.ManifestId;
    /** The inventory that is included in the manifest */
    inventory: PackagexApi.inventory.Inventory[];
    /** The ID of the location to which this manifest is being delivered */
    locationId: string;
    /** These are your metadata key value pairs added to the manifest */
    metadata?: Record<string, unknown>;
    /** The order number that either you provided to the manifest or that PackageX added automatically */
    orderNumber?: string;
    /** The ID of the organization that owns this manifest. In almost all cases, this will be your organization ID. */
    organizationId?: string;
    /** A list of all tracking numbers for this manifest. When added, trackers will be created for each tracking number which will then update the estimated_delivery property. */
    trackingNumbers?: string[];
    status?: PackagexApi.inventory.ManifestStatus;
    /** Time in epoch seconds when this item was last updated */
    updatedAt?: number;
}
