/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the manifest
 */
export type ManifestStatus = "requested" | "accepted" | "processing" | "completed" | "void";

export const ManifestStatus = {
    Requested: "requested",
    Accepted: "accepted",
    Processing: "processing",
    Completed: "completed",
    Void: "void",
} as const;
