/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Specify a label size for the returned shipping label. If not included, we'll use the default shipping label size set from the PackageX Dashboard.
 */
export type LabelSize = "4x6" | "letter" | "4x8" | "a4" | "a6";

export const LabelSize = {
    FourBySix: "4x6",
    Letter: "letter",
    FourByEight: "4x8",
    A4: "a4",
    A6: "a6",
} as const;
