/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The courier specific packaging. See https://docs.packagex.io/shipments/predefined-packages for more information
 */
export type PackageType =
    | "usps_flat_rate_envelope"
    | "usps_flat_rate_window_envelope"
    | "usps_small_flat_rate_envelope"
    | "usps_flat_rate_padded_envelope"
    | "usps_flat_rate_legal_envelope"
    | "usps_small_flat_rate_box"
    | "usps_medium_flat_rate_box_1"
    | "usps_medium_flat_rate_box_2"
    | "usps_large_flat_rate_box_1"
    | "usps_large_flat_rate_box_2"
    | "usps_large_flat_rate_box_apo_fpo";

export const PackageType = {
    UspsFlatRateEnvelope: "usps_flat_rate_envelope",
    UspsFlatRateWindowEnvelope: "usps_flat_rate_window_envelope",
    UspsSmallFlatRateEnvelope: "usps_small_flat_rate_envelope",
    UspsFlatRatePaddedEnvelope: "usps_flat_rate_padded_envelope",
    UspsFlatRateLegalEnvelope: "usps_flat_rate_legal_envelope",
    UspsSmallFlatRateBox: "usps_small_flat_rate_box",
    UspsMediumFlatRateBox1: "usps_medium_flat_rate_box_1",
    UspsMediumFlatRateBox2: "usps_medium_flat_rate_box_2",
    UspsLargeFlatRateBox1: "usps_large_flat_rate_box_1",
    UspsLargeFlatRateBox2: "usps_large_flat_rate_box_2",
    UspsLargeFlatRateBoxApoFpo: "usps_large_flat_rate_box_apo_fpo",
} as const;
