/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The type of rate that should be returned for the shipment.
 */
export type RateTypes =
    | "in_person_pickup"
    | "curbside_pickup"
    | "locker_pickup"
    | "provider_delivery"
    | "offline_delivery";

export const RateTypes = {
    InPersonPickup: "in_person_pickup",
    CurbsidePickup: "curbside_pickup",
    LockerPickup: "locker_pickup",
    ProviderDelivery: "provider_delivery",
    OfflineDelivery: "offline_delivery",
} as const;
