/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the refund on this shipment if one was requested
 */
export type RefundStatus = "requested" | "refunded" | "rejected";

export const RefundStatus = {
    Requested: "requested",
    Refunded: "refunded",
    Rejected: "rejected",
} as const;
