/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

/**
 * A shipment object
 *
 * @example
 *     {
 *         amount: 1324,
 *         billedAmount: 1023,
 *         provider: {
 *             name: "UPS",
 *             id: "2dij3dn9",
 *             logoUrl: "NA",
 *             supportEmail: "support@ups.com",
 *             supportPhone: "1-800-742-5877",
 *             supportUrl: "https://www.ups.com/us/en/support/contact-us.page",
 *             marketplace: false
 *         },
 *         createdAt: 1679245915,
 *         updatedAt: 1679245933,
 *         currency: PackageX.Currency.Usd,
 *         estimatedDelivery: 1679591515,
 *         filters: [PackageX.Filters.Completed],
 *         fulfillmentId: "efewifb31221",
 *         id: "defbei39dkna",
 *         status: PackageX.ShipmentStatus.OutForDelivery,
 *         leadTimeMins: 13,
 *         paid: true,
 *         parcels: [{
 *                 id: "ebfweufe922828",
 *                 length: 2,
 *                 width: 5,
 *                 height: 4,
 *                 weight: 1,
 *                 type: PackageX.PackageType.UspsFlatRateEnvelope
 *             }],
 *         purchasedRate: {
 *             id: "dndine29dnc9",
 *             amount: 1203,
 *             billedAmount: 9023,
 *             serviceLevel: {
 *                 id: "3bicjss933jckjcsww",
 *                 name: "Same Day",
 *                 days: 1,
 *                 estimatedDelivery: 1679591515,
 *                 terms: "Today by 9pm",
 *                 pickupAt: 1679591623
 *             },
 *             provider: {
 *                 name: "UPS",
 *                 id: "2dij3dn9",
 *                 logoUrl: "NA",
 *                 supportEmail: "support@ups.com",
 *                 supportPhone: "1-800-742-5877",
 *                 supportUrl: "https://www.ups.com/us/en/support/contact-us.page",
 *                 marketplace: false
 *             }
 *         },
 *         rates: [{
 *                 id: "dndine29dnc9",
 *                 amount: 1203,
 *                 billedAmount: 9023,
 *                 serviceLevel: {
 *                     id: "3bicjss933jckjcsww",
 *                     name: "Same Day",
 *                     days: 1,
 *                     estimatedDelivery: 1679591515,
 *                     terms: "Today by 9pm",
 *                     pickupAt: 1679591623
 *                 },
 *                 provider: {
 *                     name: "UPS",
 *                     id: "2dij3dn9",
 *                     logoUrl: "NA",
 *                     supportEmail: "support@ups.com",
 *                     supportPhone: "1-800-742-5877",
 *                     supportUrl: "https://www.ups.com/us/en/support/contact-us.page",
 *                     marketplace: false
 *                 }
 *             }],
 *         recipient: {
 *             name: "Odin Oliver",
 *             email: "odin.oliver@packagex.io",
 *             phone: "4844836699",
 *             contactId: "fwefwv28281",
 *             address: {
 *                 id: "fefewfe_9292",
 *                 hash: "efneif_2921",
 *                 line1: "600 B. Street",
 *                 line2: "Suite 300",
 *                 city: "San Diego",
 *                 state: "California",
 *                 stateCode: "CA",
 *                 country: "United States",
 *                 countryCode: "US",
 *                 postalCode: "90101",
 *                 formattedAddress: "600 B. Street, Suite 300 7th Ave, Fl 10, San Diego, California 90101",
 *                 textarea: "600 B. Street",
 *                 timezone: "PST",
 *                 verified: true
 *             }
 *         },
 *         sender: {
 *             name: "Jamie Jones",
 *             email: "jamie@packagex.io",
 *             phone: "4844836699",
 *             contactId: "cwnwif2821",
 *             address: {
 *                 id: "defnewfed_93392",
 *                 hash: "dac0efe_w9dw",
 *                 line1: "500 7th Ave",
 *                 line2: "Fl 10",
 *                 city: "New York",
 *                 state: "New York",
 *                 stateCode: "NY",
 *                 country: "United States",
 *                 countryCode: "US",
 *                 postalCode: "10018",
 *                 formattedAddress: "500 7th Ave, Fl 10, New York, NY, 10018",
 *                 textarea: "500 7th Ave",
 *                 timezone: "EST",
 *                 verified: true
 *             }
 *         },
 *         organizationId: "dwndiwqe22en2",
 *         invoiceId: "verwdwdwq3j33x2",
 *         kioskId: "fcewueek9393",
 *         trackingNumber: "wefewfwecn290ioieqoi1221239",
 *         trackingUrl: "https://www.ups.com/track?loc=en_US&requester=ST/",
 *         trackingUpdates: [{
 *                 address: {
 *                     id: "defnewfed_93392",
 *                     hash: "dac0efe_w9dw",
 *                     line1: "500 7th Ave",
 *                     line2: "Fl 10",
 *                     city: "New York",
 *                     state: "New York",
 *                     stateCode: "NY",
 *                     country: "United States",
 *                     countryCode: "US",
 *                     postalCode: "10018",
 *                     formattedAddress: "500 7th Ave, Fl 10, New York, NY, 10018",
 *                     textarea: "500 7th Ave",
 *                     timezone: "EST",
 *                     verified: true
 *                 },
 *                 status: PackageX.ShipmentStatus.InTransit,
 *                 message: "In Transit",
 *                 images: [],
 *                 createdAt: 1679591515,
 *                 updatedAt: 1679591623,
 *                 event: PackageX.ShipmentEvent.TrackingUpdated
 *             }, {
 *                 address: {
 *                     id: "defnewfed_93392",
 *                     hash: "dac0efe_w9dw",
 *                     line1: "500 7th Ave",
 *                     line2: "Fl 10",
 *                     city: "New York",
 *                     state: "New York",
 *                     stateCode: "NY",
 *                     country: "United States",
 *                     countryCode: "US",
 *                     postalCode: "10018",
 *                     formattedAddress: "500 7th Ave, Fl 10, New York, NY, 10018",
 *                     textarea: "500 7th Ave",
 *                     timezone: "EST",
 *                     verified: true
 *                 },
 *                 status: PackageX.ShipmentStatus.OutForDelivery,
 *                 message: "Out for Delivery",
 *                 images: [],
 *                 createdAt: 1679591515,
 *                 updatedAt: 1679591623,
 *                 event: PackageX.ShipmentEvent.TrackingUpdated
 *             }],
 *         coordinates: [37.7749, 122.4194]
 *     }
 */
export interface Shipment {
    /** The amount that will be collected from a customer. This includes any upcharges or discounts you have added to the price on the PackageX Dashboard. */
    amount?: number;
    /** The amount that your organization will be billed for this rate. */
    billedAmount?: number;
    provider?: PackageX.Provider;
    /** Time in epoch seconds when this shipment was created. */
    createdAt: number;
    /** Time in epoch seconds when this shipment was last updated. */
    updatedAt: number;
    currency: PackageX.Currency;
    /** Time in epoch seconds when we estimate the delivery will occur. */
    estimatedDelivery?: number;
    filters: PackageX.Filters[];
    /** The ID of the fulfillment that created this shipment. */
    fulfillmentId: string;
    /** The unique ID for the shipment */
    id: PackageX.ShipmentId;
    refundStatus?: PackageX.RefundStatus;
    status: PackageX.ShipmentStatus;
    /** The amount of lead time needed to prepare the shipment for an on-demand courier. This is only applicable for same-day shipments and indicated how much advance notice is required between the shipping provider and sender before a courier will be dispatched. */
    leadTimeMins: number;
    /** Custom key value pairs that the organization is able to add to this shipment */
    metadata?: Record<string, unknown>;
    options?: PackageX.ShipmentOptions;
    /** If the shipment has been paid for */
    paid: boolean;
    /** The individual packages that are part of this shipment. */
    parcels: PackageX.inventory.Parcel[];
    /** A user generated reference for this payment. Will be included in invoices. */
    paymentReference?: string;
    purchasedRate?: PackageX.Rate;
    /** All of the rates that were returned when creating this shipment */
    rates: PackageX.Rate[];
    recipient: PackageX.Recipient;
    sender: PackageX.Sender;
    /** Seconds from epoch when this shipment will be picked up, if pickup is part of the rate's service level */
    pickupAt?: number;
    /** The ID of the organization that owns this shipment */
    organizationId: string;
    /** The url for the shipping label */
    labelUrl?: string;
    /** The ID of the invoice for this shipment */
    invoiceId: string;
    /** This kiosk that was used to generate this shipment. */
    kioskId: string;
    /** The tracking number for this shipment. */
    trackingNumber: string;
    /** The url for the end user to track their shipment */
    trackingUrl: string;
    feedback?: PackageX.ShipmentFeedback;
    /** A list of all tracking updates that occurred for this shipment from oldest to newest */
    trackingUpdates: PackageX.TrackingUpdate[];
    coordinates: number[];
    search?: PackageX.Search;
}
