/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type ShipmentEvent =
    /**
     * Shipping rates were generated */
    | "shipment.rates_generated"
    /**
     * The shipment expired.
     * To protect on demand couriers, shipments need to be purchased within 15 minutes
     *  */
    | "shipment.expired"
    /**
     * When the shipment is purchased successfully */
    | "shipment.purchased"
    /**
     * The provider has updated the shipment's status */
    | "shipment.tracking_updated"
    /**
     * The shipment was canceled, usually because the sender requested a refund */
    | "shipment.canceled"
    /**
     * The shipment was successfully refunded. */
    | "shipment.refunded"
    /**
     * The live location was updated in the shipment, but the status was not changed */
    | "shipment.coordinates_updated";

export const ShipmentEvent = {
    RatesGenerated: "shipment.rates_generated",
    Expired: "shipment.expired",
    Purchased: "shipment.purchased",
    TrackingUpdated: "shipment.tracking_updated",
    Canceled: "shipment.canceled",
    Refunded: "shipment.refunded",
    CoordinatesUpdated: "shipment.coordinates_updated",
} as const;
