/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The current status for the shipment. It's the same status as the latest tracking_update just surfaced for convenience. See https://docs.packagex.io/shipments/statuses for more info on statuses.
 */
export type ShipmentStatus =
    | "rates_generated"
    | "created"
    | "address_issue"
    | "provider_at_pickup"
    | "contact_provider"
    | "delayed"
    | "delivery_attempted"
    | "delivery_rescheduled"
    | "delivery_scheduled"
    | "out_for_delivery"
    | "package_accepted"
    | "package_at_waypoint"
    | "in_transit"
    | "pickup_available"
    | "provider_at_dropoff"
    | "package_damaged"
    | "delivered"
    | "return_to_sender"
    | "package_undeliverable"
    | "package_lost"
    | "canceled";

export const ShipmentStatus = {
    RatesGenerated: "rates_generated",
    Created: "created",
    AddressIssue: "address_issue",
    ProviderAtPickup: "provider_at_pickup",
    ContactProvider: "contact_provider",
    Delayed: "delayed",
    DeliveryAttempted: "delivery_attempted",
    DeliveryRescheduled: "delivery_rescheduled",
    DeliveryScheduled: "delivery_scheduled",
    OutForDelivery: "out_for_delivery",
    PackageAccepted: "package_accepted",
    PackageAtWaypoint: "package_at_waypoint",
    InTransit: "in_transit",
    PickupAvailable: "pickup_available",
    ProviderAtDropoff: "provider_at_dropoff",
    PackageDamaged: "package_damaged",
    Delivered: "delivered",
    ReturnToSender: "return_to_sender",
    PackageUndeliverable: "package_undeliverable",
    PackageLost: "package_lost",
    Canceled: "canceled",
} as const;
