/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type SpecialHandling =
    | "confidential"
    | "fragile"
    | "urgent"
    | "perishable"
    | "legal_document"
    | "oversized"
    | "dry_ice"
    | "batteries"
    | "time_sensitive"
    | "signature";

export const SpecialHandling = {
    Confidential: "confidential",
    Fragile: "fragile",
    Urgent: "urgent",
    Perishable: "perishable",
    LegalDocument: "legal_document",
    Oversized: "oversized",
    DryIce: "dry_ice",
    Batteries: "batteries",
    TimeSensitive: "time_sensitive",
    Signature: "signature",
} as const;
