/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../../../core";

export const InventoryLevel: core.serialization.ObjectSchema<
    serializers.inventory.InventoryLevel.Raw,
    PackageX.inventory.InventoryLevel
> = core.serialization.object({
    id: core.serialization.string(),
    locationId: core.serialization.property("location_id", core.serialization.string()),
    layoutId: core.serialization.property("layout_id", core.serialization.string().optional()),
    layoutName: core.serialization.property("layout_name", core.serialization.string().optional()),
    verifiedQty: core.serialization.property("verified_qty", core.serialization.number().optional()),
    damagedQty: core.serialization.property("damaged_qty", core.serialization.number().optional()),
    manifestedQty: core.serialization.property("manifested_qty", core.serialization.number().optional()),
    reservedQty: core.serialization.property("reserved_qty", core.serialization.number().optional()),
});

export declare namespace InventoryLevel {
    interface Raw {
        id: string;
        location_id: string;
        layout_id?: string | null;
        layout_name?: string | null;
        verified_qty?: number | null;
        damaged_qty?: number | null;
        manifested_qty?: number | null;
        reserved_qty?: number | null;
    }
}
