/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface CreateItemRequest {
    /** The name of the item (only required property) */
    name: string;
    /** Either SKU or GTIN most likely on the barcode of items so it's best to include this so that barcode scanners play nicely. */
    sku?: string;
    /** Either SKU or GTIN most likely on the barcode of items so it's best to include this so that barcode scanners play nicely. */
    gtin?: string;
    /** If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item */
    packagedLength?: number;
    /** If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item */
    packagedWidth?: number;
    /** If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item */
    packagedHeight?: number;
    /** If you're planning to do fulfillments, this property will be required, so it is easier to add it on the item */
    packagedWeight?: number;
}
