/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

export interface UpdateItemRequest {
    /** Updated name */
    name?: string;
    levels?: PackageX.inventory.InventoryLevel[];
}
