/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A sudo status given to the delivery to know what is happening with the delivery.
 */
export type Filters = "completed" | "outstanding" | "exception";

export const Filters = {
    Completed: "completed",
    Outstanding: "outstanding",
    Exception: "exception",
} as const;
