/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface Options {
    /** If the extracted sender and recipient addresses should be run through the address parser. */
    parseAddresses: boolean;
    /** If you want the extracted sender and recipient fields to be matched to existing contacts in your organization. */
    matchContacts: boolean;
}
