/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * Details about a shipping provider for a given rate or shipment
 *
 * @example
 *     {
 *         name: "UPS",
 *         id: "2dij3dn9",
 *         logoUrl: "NA",
 *         supportEmail: "support@ups.com",
 *         supportPhone: "1-800-742-5877",
 *         supportUrl: "https://www.ups.com/us/en/support/contact-us.page",
 *         marketplace: false
 *     }
 */
export interface Provider {
    /** The name of the provider */
    name: string;
    /** Unique ID of the provider */
    id: string;
    /** The url for the provider's logo */
    logoUrl: string;
    /** The contact email provided by the shipping provider */
    supportEmail?: string;
    /** The contact phone provided by the shipping provider */
    supportPhone?: string;
    /** The contact website provided by the shipping provider */
    supportUrl: string;
    /** A support reference code that some providers use to help customers. */
    supportReference?: string;
    /** If this shipping provider came from the PackageX marketplace. Typically large providers like FedEx, UPS, USPS, etc are not from the marketplace and same-day courier are not. */
    marketplace: boolean;
}
