/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

/**
 * The information about the shipment recipient
 *
 * @example
 *     {
 *         name: "Odin Oliver",
 *         email: "odin.oliver@packagex.io",
 *         phone: "4844836699",
 *         contactId: "fwefwv28281"
 *     }
 */
export interface Recipient {
    address?: PackageX.Address;
    /** The recipient's name */
    name: string;
    /** The recipient's email */
    email: string;
    /** The recipient's phone */
    phone: string;
    /** The ID of the contact if one was used to create this recipient. */
    contactId: string;
}
