/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The information about the shipment recipient
 *
 * @example
 *     {
 *         name: "Odin Oliver",
 *         email: "odin.oliver@packagex.io",
 *         phone: "4844836699",
 *         contactId: "fwefwv28281",
 *         address: {
 *             id: "fefewfe_9292",
 *             hash: "efneif_2921",
 *             line1: "600 B. Street",
 *             line2: "Suite 300",
 *             city: "San Diego",
 *             state: "California",
 *             stateCode: "CA",
 *             country: "United States",
 *             countryCode: "US",
 *             postalCode: "90101",
 *             formattedAddress: "600 B. Street, Suite 300 7th Ave, Fl 10, San Diego, California 90101",
 *             textarea: "600 B. Street",
 *             timezone: "PST",
 *             verified: true
 *         }
 *     }
 */
export interface Recipient {
    address: PackagexApi.ParsedAddress;
    /** The recipient's name */
    name: string;
    /** The recipient's email */
    email: string;
    /** The recipient's phone */
    phone: string;
    /** The ID of the contact if one was used to create this recipient. */
    contactId: string;
}
