/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A special property that will be included if searching through shipments.
 */
export interface Search {
    /** The ID of the shipment. */
    id: string;
    /** The tracking number. */
    trackingNumber: string;
    /** The sender's name. It will also match common nicknames. */
    senderName: string;
    /** The sender's email. */
    senderEmail: string;
    /** The sender's phone. */
    senderPhone: string;
    /** The sender's full address string. */
    senderFormattedAddress: string;
    /** The recipient's name. It will also match common nicknames. */
    recipientName: string;
    /** The recipient's email. */
    recipientEmail: string;
    /** The recipient's phone. */
    recipientPhone: string;
    /** The recipient's full address string. */
    recipientFormattedAddress: string;
    /** The shipping provider's name. */
    providerName: string;
    /** The shipping provider's ID */
    providerId: string;
    /** Any custom metadata that you have added */
    metadata?: Record<string, unknown>;
    /** A number from 0 - 1 about how relevant the result was to the search query, with 1 being a perfect match. */
    relevanceScore: number;
}
