/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

/**
 * The information about the shipment sender, which is normally the organization using this API
 *
 * @example
 *     {
 *         name: "Jamie Jones",
 *         email: "jamie@packagex.io",
 *         phone: "4844836699",
 *         contactId: "cwnwif2821"
 *     }
 */
export interface Sender {
    address: PackageX.Address;
    addressLine2?: string;
    /** The sender's name */
    name: string;
    /** The sender's email */
    email: string;
    /** The sender's phone */
    phone: string;
    /** The sender's unique packagex ID */
    contactId: string;
}
