/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackageX } from "@fern-api/packagex";

/**
 * The information about the shipment sender, which is normally the organization using this API
 *
 * @example
 *     {
 *         name: "Jamie Jones",
 *         email: "jamie@packagex.io",
 *         phone: "4844836699",
 *         contactId: "cwnwif2821",
 *         address: {
 *             id: "defnewfed_93392",
 *             hash: "dac0efe_w9dw",
 *             line1: "500 7th Ave",
 *             line2: "Fl 10",
 *             city: "New York",
 *             state: "New York",
 *             stateCode: "NY",
 *             country: "United States",
 *             countryCode: "US",
 *             postalCode: "10018",
 *             formattedAddress: "500 7th Ave, Fl 10, New York, NY, 10018",
 *             textarea: "500 7th Ave",
 *             timezone: "EST",
 *             verified: true
 *         }
 *     }
 */
export interface Sender {
    address: PackageX.ParsedAddress;
    addressLine2?: string;
    /** The sender's name */
    name: string;
    /** The sender's email */
    email: string;
    /** The sender's phone */
    phone: string;
    /** The sender's unique packagex ID */
    contactId: string;
}
