/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Shipments } from "./api/resources/shipments/client/Client";

export declare namespace PackagexApiClient {
    interface Options {
        environment?: environments.PackagexApiEnvironment | string;
        securityScheme?: core.Supplier<string>;
    }
}

export class PackagexApiClient {
    constructor(private readonly options: PackagexApiClient.Options) {}

    private _shipments: Shipments | undefined;

    public get shipments(): Shipments {
        return (this._shipments ??= new Shipments(this.options));
    }
}
