/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments";
import * as core from "./core";
import { Address } from "./api/resources/address/client/Client";
import { Inventory } from "./api/resources/inventory/client/Client";
import { Shipment } from "./api/resources/shipment/client/Client";

export declare namespace PackageXClient {
    interface Options {
        environment?: environments.PackageXEnvironment | string;
        apiKey: core.Supplier<string>;
    }
}

export class PackageXClient {
    constructor(private readonly options: PackageXClient.Options) {}

    private _address: Address | undefined;

    public get address(): Address {
        return (this._address ??= new Address(this.options));
    }

    private _inventory: Inventory | undefined;

    public get inventory(): Inventory {
        return (this._inventory ??= new Inventory(this.options));
    }

    private _shipment: Shipment | undefined;

    public get shipment(): Shipment {
        return (this._shipment ??= new Shipment(this.options));
    }
}
