/**
 * This file was auto-generated by Fern from our API Definition.
 */

export const PackagexApiEnvironment = {
    Production: "https://api.packagex.io",
    Sandbox: "https://sandbox.packagex.io",
} as const;

export type PackagexApiEnvironment = typeof PackagexApiEnvironment.Production | typeof PackagexApiEnvironment.Sandbox;
