/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

export interface FulfillmentResponse extends PackagexApi.Response {
    data: PackagexApi.inventory.Fulfillment;
}
