/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * The fulfillment model represents a unique fulfillment containing the inventory that was sent to the recipient.
 *
 * @example
 *     {
 *         id: "ful_dwdh3239ubcejbcjd",
 *         createdAt: 1679591515,
 *         locationId: "loc_afnHMjVUn3gnrvxU5zMvkX",
 *         recipient: {
 *             name: "Odin Oliver",
 *             email: "odin.oliver@packagex.io",
 *             phone: "4844836699",
 *             contactId: "fwefwv28281",
 *             address: {
 *                 id: "fefewfe_9292",
 *                 hash: "efneif_2921",
 *                 line1: "600 B. Street",
 *                 line2: "Suite 300",
 *                 city: "San Diego",
 *                 state: "California",
 *                 stateCode: "CA",
 *                 country: "United States",
 *                 countryCode: "US",
 *                 postalCode: "90101",
 *                 formattedAddress: "600 B. Street, Suite 300 7th Ave, Fl 10, San Diego, California 90101",
 *                 textarea: "600 B. Street",
 *                 timezone: "PST",
 *                 verified: true
 *             }
 *         },
 *         inventory: [{
 *                 id: "item_5og9NZ92SYzHKFTPYSEnVK",
 *                 verifiedQty: 25
 *             }, {
 *                 id: "item_1nCNpqtyepe48BMNhzmW54",
 *                 verifiedQty: 50,
 *                 packagedLength: 2,
 *                 packagedWidth: 3,
 *                 packagedHeight: 4,
 *                 packagedWeight: 6
 *             }, {
 *                 name: "Custom Item",
 *                 verifiedQty: 5,
 *                 packagedLength: 2,
 *                 packagedWidth: 3,
 *                 packagedHeight: 4,
 *                 packagedWeight: 6,
 *                 id: "item_1wefewf33232hzmW54",
 *                 sku: "237489237489",
 *                 imageUrl: "https://i.imgur.com/FKmX7dt.gif"
 *             }]
 *     }
 *
 * @example
 *     {
 *         id: "ful_dwdh3239ubcejbcjd",
 *         createdAt: 1679591515,
 *         locationId: "loc_afnHMjVUn3gnrvxU5zMvkX",
 *         parcels: [{
 *                 id: "prcl_fnweifnief9292",
 *                 length: 10,
 *                 width: 10,
 *                 height: 10
 *             }],
 *         recipient: {
 *             name: "Odin Oliver",
 *             email: "odin.oliver@packagex.io",
 *             phone: "4844836699",
 *             contactId: "fwefwv28281",
 *             address: {
 *                 id: "fefewfe_9292",
 *                 hash: "efneif_2921",
 *                 line1: "600 B. Street",
 *                 line2: "Suite 300",
 *                 city: "San Diego",
 *                 state: "California",
 *                 stateCode: "CA",
 *                 country: "United States",
 *                 countryCode: "US",
 *                 postalCode: "90101",
 *                 formattedAddress: "600 B. Street, Suite 300 7th Ave, Fl 10, San Diego, California 90101",
 *                 textarea: "600 B. Street",
 *                 timezone: "PST",
 *                 verified: true
 *             }
 *         },
 *         inventory: [{
 *                 id: "item_5og9NZ92SYzHKFTPYSEnVK",
 *                 verifiedQty: 25
 *             }, {
 *                 id: "item_1nCNpqtyepe48BMNhzmW54",
 *                 verifiedQty: 50,
 *                 packagedLength: 2,
 *                 packagedWidth: 3,
 *                 packagedHeight: 4,
 *                 packagedWeight: 6
 *             }, {
 *                 name: "Custom Item",
 *                 verifiedQty: 5,
 *                 packagedLength: 2,
 *                 packagedWidth: 3,
 *                 packagedHeight: 4,
 *                 packagedWeight: 6,
 *                 id: "item_fewf44t43g4g43g4g4",
 *                 sku: "237489237489",
 *                 imageUrl: "https://i.imgur.com/FKmX7dt.gif"
 *             }]
 *     }
 *
 * @example
 *     {
 *         id: "ful_dwdh3239ubcejbcjd",
 *         status: PackagexApi.inventory.FulfillmentStatus.Packed,
 *         createdAt: 1679591515,
 *         locationId: "loc_afnHMjVUn3gnrvxU5zMvkX",
 *         parcels: [{
 *                 id: "prcl_fnweifnief9292",
 *                 length: 10,
 *                 width: 10,
 *                 height: 10,
 *                 inventory: {
 *                     id: "item_1nCNpqtyepe48BMNhzmW54",
 *                     verifiedQty: 2
 *                 }
 *             }],
 *         recipient: {
 *             name: "Odin Oliver",
 *             email: "odin.oliver@packagex.io",
 *             phone: "4844836699",
 *             contactId: "fwefwv28281",
 *             address: {
 *                 id: "fefewfe_9292",
 *                 hash: "efneif_2921",
 *                 line1: "600 B. Street",
 *                 line2: "Suite 300",
 *                 city: "San Diego",
 *                 state: "California",
 *                 stateCode: "CA",
 *                 country: "United States",
 *                 countryCode: "US",
 *                 postalCode: "90101",
 *                 formattedAddress: "600 B. Street, Suite 300 7th Ave, Fl 10, San Diego, California 90101",
 *                 textarea: "600 B. Street",
 *                 timezone: "PST",
 *                 verified: true
 *             }
 *         },
 *         inventory: [{
 *                 id: "item_5og9NZ92SYzHKFTPYSEnVK",
 *                 verifiedQty: 25
 *             }, {
 *                 id: "item_1nCNpqtyepe48BMNhzmW54",
 *                 verifiedQty: 50,
 *                 packagedLength: 2,
 *                 packagedWidth: 3,
 *                 packagedHeight: 4,
 *                 packagedWeight: 6
 *             }, {
 *                 name: "Custom Item",
 *                 verifiedQty: 5,
 *                 packagedLength: 2,
 *                 packagedWidth: 3,
 *                 packagedHeight: 4,
 *                 packagedWeight: 6,
 *                 sku: "237489237489",
 *                 id: "item_1nCNpqtyepe48BMNhzmW54",
 *                 imageUrl: "https://i.imgur.com/FKmX7dt.gif"
 *             }]
 *     }
 */
export interface Fulfillment {
    /** If the fulfillment gets canceled, a reason can be optionally provided here. */
    cancelReason?: string;
    /** Time in epoch seconds when this resource was created */
    createdAt: number;
    /** Time in epoch seconds by which this fulfillment should be completed */
    completeBy?: number;
    /** The unique ID given to this fulfillment prefixed with ful_ */
    id: PackagexApi.inventory.FulfillmentId;
    /** The inventory that needs to be shipped in this fulfillment */
    inventory: PackagexApi.inventory.Inventory[];
    /** The URL of the shipping label that gets generated when the fulfillment is completed */
    labelUrl?: string;
    /** The ID of the location to which this manifest is being delivered */
    locationId: string;
    /** These are your metadata key value pairs added to the manifest */
    metadata?: Record<string, unknown>;
    /** The order number that either you provided to the fulfillment or that PackageX added automatically */
    orderNumber?: string;
    /** The ID of the organization that owns this fulfillment. In almost all cases, this will be your organization ID. */
    organizationId?: string;
    /** A list of the recommended way(s) to package to product into parcels if any shipping boxes are predefined in the settings. This is currently an empty array for all users. */
    packagingRecommendations?: string[];
    /** The URL to the PDF of the packing slip for all items added to inventory */
    packingSlipUrl?: string[];
    /** All parcels in the fulfillment and the inventory packed within them */
    parcels?: PackagexApi.inventory.Parcel[];
    /** Time in epoch seconds when shipping rates were generated for this fulfillment. Shipping rates are only valid for 15 minutes after which new rates must be fetched. */
    ratesGeneratedAt?: number;
    /** Details about the contact receiving this shipment */
    recipient?: PackagexApi.Recipient;
    /** Details about the contact sending this shipment */
    sender?: PackagexApi.Sender;
    /** The ID of the shipment associated with this fulfillment, prefixed with ship_ */
    shipmentId?: string;
    shipmentRateType?: PackagexApi.inventory.ShipmentRateType;
    status?: PackagexApi.inventory.FulfillmentStatus;
    /** Time in epoch seconds when this resource was last updated */
    updatedAt?: number;
}
