/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * The status of the fulfillment
 */
export type FulfillmentStatus = "created" | "processing" | "packed" | "completed" | "canceled";

export const FulfillmentStatus = {
    Created: "created",
    Processing: "processing",
    Packed: "packed",
    Completed: "completed",
    Canceled: "canceled",
} as const;
