/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * A list of enumerated strings to give more context to special items.
 */
export type InventoryAttributes = "alcohol" | "marijuana" | "pharma" | "dry_ice" | "lithium";

export const InventoryAttributes = {
    Alcohol: "alcohol",
    Marijuana: "marijuana",
    Pharma: "pharma",
    DryIce: "dry_ice",
    Lithium: "lithium",
} as const;
