/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

/**
 * A parcel or package that will be included in a shipment
 *
 * @example
 *     {
 *         id: "ebfweufe922828",
 *         length: 2,
 *         width: 5,
 *         height: 4,
 *         weight: 1,
 *         type: PackagexApi.PackageType.UspsFlatRateEnvelope
 *     }
 */
export interface Parcel {
    attributes?: PackagexApi.inventory.InventoryAttributes[];
    /** The unique ID assigned to the parcel beginning with prcl_ */
    id: PackagexApi.inventory.ParcelId;
    /** The length of the package in inches */
    length: number;
    /** The width of the package in inches */
    width: number;
    /** The height of the package in inches */
    height: number;
    /** The weight of the package in pounds */
    weight?: number;
    type?: PackagexApi.PackageType;
    /** Any special handing instructions provided. Not all shipping providers support these */
    specialHandling?: string;
    /** The tracking number for this parcel if a shipment was purchased */
    trackingNumber?: string;
    /** The shipping label PDF for this parcel if a shipment was purchased */
    labelUrl?: string;
    /** The inventory packed inside of the parcel */
    inventory?: PackagexApi.inventory.Inventory;
}
