/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Filters: core.serialization.Schema<serializers.Filters.Raw, PackageX.Filters> = core.serialization.enum_([
    "completed",
    "outstanding",
    "exception",
]);

export declare namespace Filters {
    type Raw = "completed" | "outstanding" | "exception";
}
