/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Options: core.serialization.ObjectSchema<serializers.Options.Raw, PackagexApi.Options> =
    core.serialization.object({
        parseAddresses: core.serialization.property("parse_addresses", core.serialization.boolean()),
        matchContacts: core.serialization.property("match_contacts", core.serialization.boolean()),
    });

export declare namespace Options {
    interface Raw {
        parse_addresses: boolean;
        match_contacts: boolean;
    }
}
