/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackageX } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Recipient: core.serialization.ObjectSchema<serializers.Recipient.Raw, PackageX.Recipient> =
    core.serialization.object({
        address: core.serialization.lazy(async () => (await import("../../..")).Address).optional(),
        name: core.serialization.string(),
        email: core.serialization.string(),
        phone: core.serialization.string(),
        contactId: core.serialization.property("contact_id", core.serialization.string()),
    });

export declare namespace Recipient {
    interface Raw {
        address?: serializers.Address.Raw | null;
        name: string;
        email: string;
        phone: string;
        contact_id: string;
    }
}
