/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as serializers from "../../..";
import { PackagexApi } from "@fern-api/packagex";
import * as core from "../../../../core";

export const Recipient: core.serialization.ObjectSchema<serializers.Recipient.Raw, PackagexApi.Recipient> =
    core.serialization.object({
        address: core.serialization.lazyObject(async () => (await import("../../..")).ParsedAddress),
        name: core.serialization.string(),
        email: core.serialization.string(),
        phone: core.serialization.string(),
        contactId: core.serialization.property("contact_id", core.serialization.string()),
    });

export declare namespace Recipient {
    interface Raw {
        address: serializers.ParsedAddress.Raw;
        name: string;
        email: string;
        phone: string;
        contact_id: string;
    }
}
