/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { PackagexApi } from "@fern-api/packagex";

export interface UpdateManifestStatusRequest {
    status: PackagexApi.inventory.ManifestStatus;
}
